### ISSUE TITLE
Dockerfile to make compilation easier

### ISSUE THREAD

**Issue by RodionGork** [pawelbiernacki/chomik#1]
Paweł, Hi!

Some time ago I complained (at 4programmers.net forum) that building the thing is a bit difficult. Sorry for delay, but I got back to the matter and constructed a small dockerfile which installs all necessary system dependencies (which I found from re-running `configure` and adding them one by one). Then compiling is done just with two simple commands (to build image and to run configure and make using this image).

I put details at forum also https://4programmers.net/Forum/Inne/374920-kompilacja_chomika_jest_zbyt_latwa_stworzylem_dockerfile_z_zaleznosciami

however this lacks the final step of `make install` (though I'm able to use compiled `chomik` providing path to library to it - it runs on given examples well).

I wonder if it may be useful to add this file (and shell-file with two commands to build stuff) as a pull-request.

However perhaps it would be good also to make something similar for windows build, but I don't know how.

Another good option could be to make precompiled binaries and upload them as "releases"... at least for Linux and Windows on amd64.

Also I wonder if it is possible not to use `libchomik.so`, instead making one fat `chomik` executable (static compilation)?

**Comment by pawelbiernacki** [comment]
Thanks a lot. I will think about the precompiled releases.
